default_language_version:
  python: python3
ci:
  autofix_commit_msg: "\U0001F3A8 [pre-commit.ci] Auto format from pre-commit.com hooks"
  autoupdate_commit_msg: '⬆ [pre-commit.ci] pre-commit autoupdate'
  autofix_prs: true
  autoupdate_schedule: quarterly
repos:
  - repo: 'https://github.com/MarcoGorelli/absolufy-imports'
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
        args:
          - '--unsafe'
      - id: end-of-file-fixer
      - id: pretty-format-json
      - id: trailing-whitespace
  - repo: 'https://github.com/asottile/pyupgrade'
    rev: v2.37.2
    hooks:
      - id: pyupgrade
        args:
          - '--py38-plus'
          - '--keep-runtime-typing'
  - repo: 'https://github.com/myint/autoflake'
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          - '--recursive'
          - '--in-place'
          - '--expand-star-imports'
          - '--exclude'
          - __init__.py
          - '--remove-duplicate-keys'
  - repo: 'https://github.com/pycqa/isort'
    rev: 5.10.1
    hooks:
      - id: isort
        args:
          - '--profile=black'
          - '--line-length=98'
        name: isort (python)
      - id: isort
        name: isort (cython)
        types:
          - cython
      - id: isort
        name: isort (pyi)
        types:
          - pyi
  - repo: 'https://github.com/psf/black'
    rev: 22.6.0
    hooks:
      - id: black
        args:
          - '--line-length=98'
          - '--exclude'
          - __init__.py
  - repo: 'https://github.com/asottile/blacken-docs'
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        args:
          - '--line-length=98'
        additional_dependencies:
          - black==22.3.0
  - repo: 'https://github.com/asottile/yesqa'
    rev: v1.3.0
    hooks:
      - id: yesqa
  - repo: 'https://github.com/executablebooks/mdformat'
    rev: 0.7.14
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat_frontmatter
        exclude: CHANGELOG.md
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.4.0
    hooks:
    - id: nbqa-black
      name: nbqa-black
    - id: nbqa-pyupgrade
      args: [--py38-plus]
    - id: nbqa-isort
      name: isort nbqa-isort
